// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_explorer.h"
#include "screens/ui_audioplayer.h"
#include "screens/ui_bt_select.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);
void cb_btn_back(lv_event_t *e);
void cb_btn_play_pause(lv_event_t *e);
void cb_btn_prev(lv_event_t *e);
void cb_btn_next(lv_event_t *e);
void cb_slider_progress(lv_event_t *e);
void cb_slider_volume(lv_event_t *e);
void cb_rescan_clicked(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
