// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "bt_audio.h"

bool ui_is_playing;
extern lv_obj_t * lbl_volume_icon;

void cb_btn_back(lv_event_t *e) {
    lv_scr_load_anim(ui_explorer, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, false);

    ui_is_playing = false;
    lv_label_set_text(ui_lblBtnPlayPause, LV_SYMBOL_PLAY);
    bt_audio_stop();
}

void cb_btn_play_pause(lv_event_t *e) {
    ui_is_playing = !ui_is_playing;

    if (ui_is_playing) {
        lv_label_set_text(ui_lblBtnPlayPause, LV_SYMBOL_PAUSE);
        bt_audio_resume();
    } else {
        lv_label_set_text(ui_lblBtnPlayPause, LV_SYMBOL_PLAY);
        bt_audio_pause();
    }
}

void cb_btn_prev(lv_event_t *e) {
    // TODO: audio_prev();
}

void cb_btn_next(lv_event_t *e) {
    // TODO: audio_next();
}

void cb_slider_progress(lv_event_t *e) {
    int pct = lv_slider_get_value(ui_sliderProgress);
    bt_audio_playback_pos_t p = {0};

    bt_audio_get_position(&p);

    uint32_t seek_ms = ((p.duration_ms * pct) / 100) + ((p.duration_ms * pct) % 100);
    bt_audio_seek(seek_ms);
}

void cb_slider_volume(lv_event_t *e) {
    int vol = lv_slider_get_value(ui_sliderVolume);

    // Đổi icon theo mức volume
    if (vol == 0) {
        lv_label_set_text(lbl_volume_icon, LV_SYMBOL_VOLUME_MID);
    } else if (vol < 50) {
        lv_label_set_text(lbl_volume_icon, LV_SYMBOL_VOLUME_MID);
    } else {
        lv_label_set_text(lbl_volume_icon, LV_SYMBOL_VOLUME_MAX);
    }

    bt_audio_set_volume(vol);
}

extern void ui_bt_select_start_scan(void);

void cb_rescan_clicked(lv_event_t *e) {
    ui_bt_select_start_scan();
}
