// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_audioplayer;
lv_obj_t * ui_audioplayer;
lv_obj_t * ui_lblSongName;
lv_obj_t * ui_sliderProgress;
lv_obj_t * ui_lblTimeElapsed;
lv_obj_t * ui_lblTimeTotal;
lv_obj_t * ui_btnPlayPause;
lv_obj_t * ui_lblBtnPlayPause;
lv_obj_t * ui_sliderVolume;
lv_obj_t * lbl_volume_icon;
lv_obj_t * lbl_loop;

static lv_obj_t * btn_back;
static lv_obj_t * btn_prev;
static lv_obj_t * btn_next;
static lv_obj_t * btn_loop;

// Styles
static lv_style_t style_screen_bg;
static lv_style_t style_song_name;
static lv_style_t style_ctrl_btn;
static lv_style_t style_ctrl_btn_pressed;
static lv_style_t style_ctrl_btn_pressed_2;
static lv_style_t style_progress_main;
static lv_style_t style_progress_indicator;
static lv_style_t style_progress_knob;

static void init_player_styles(void) {
    // --- Screen background: gradient tối ---
    lv_style_init(&style_screen_bg);
    lv_style_set_bg_color(&style_screen_bg, lv_color_hex(0x1A1A2E));
    lv_style_set_bg_opa(&style_screen_bg, LV_OPA_COVER);

    // --- Song name ---
    lv_style_init(&style_song_name);
    lv_style_set_text_color(&style_song_name, lv_color_hex(0xFFFFFF));

    // --- Buttons ---
    lv_style_init(&style_ctrl_btn);
    lv_style_set_bg_opa(&style_ctrl_btn, LV_OPA_TRANSP);
    lv_style_set_border_width(&style_ctrl_btn, 0);
    lv_style_set_shadow_width(&style_ctrl_btn, 0);
    lv_style_set_text_color(&style_ctrl_btn, lv_color_hex(0xFFFFFF));

    lv_style_init(&style_ctrl_btn_pressed);
    lv_style_set_bg_opa(&style_ctrl_btn_pressed, LV_OPA_20);
    lv_style_set_bg_color(&style_ctrl_btn_pressed, lv_color_hex(0xFFFFFF));
    lv_style_set_radius(&style_ctrl_btn_pressed, LV_RADIUS_CIRCLE);

    lv_style_init(&style_ctrl_btn_pressed_2);
    lv_style_set_bg_opa(&style_ctrl_btn_pressed_2, LV_OPA_20);
    lv_style_set_bg_color(&style_ctrl_btn_pressed, lv_color_hex(0xFFFFFF));
    lv_style_set_radius(&style_ctrl_btn_pressed, 5);

    // --- Progress bar: track (nền) ---
    lv_style_init(&style_progress_main);
    lv_style_set_bg_color(&style_progress_main, lv_color_hex(0x333355));
    lv_style_set_bg_opa(&style_progress_main, LV_OPA_COVER);
    lv_style_set_radius(&style_progress_main, 4);
    lv_style_set_height(&style_progress_main, 6);

    // --- Progress bar: filled portion ---
    lv_style_init(&style_progress_indicator);
    lv_style_set_bg_color(&style_progress_indicator, lv_color_hex(0x4FC3F7));
    lv_style_set_bg_opa(&style_progress_indicator, LV_OPA_COVER);
    lv_style_set_radius(&style_progress_indicator, 4);

    // --- Progress bar: knob ---
    lv_style_init(&style_progress_knob);
    lv_style_set_bg_color(&style_progress_knob, lv_color_hex(0xFFFFFF));
    lv_style_set_bg_opa(&style_progress_knob, LV_OPA_COVER);
    lv_style_set_pad_all(&style_progress_knob, 5);       // kích thước knob
    lv_style_set_radius(&style_progress_knob, LV_RADIUS_CIRCLE);
}

void ui_audioplayer_screen_init(void)
{
    init_player_styles();

    ui_audioplayer = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_audioplayer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_remove_flag(ui_audioplayer, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_style(ui_audioplayer, &style_screen_bg, 0);

    // ============================================================
    // Back button (góc trái trên)
    // ============================================================
    btn_back = lv_btn_create(ui_audioplayer);
    lv_obj_set_size(btn_back, 40, 30);
    lv_obj_align(btn_back, LV_ALIGN_TOP_LEFT, 5, 5);
    lv_obj_add_style(btn_back, &style_ctrl_btn, LV_STATE_DEFAULT);
    lv_obj_add_style(btn_back, &style_ctrl_btn_pressed_2, LV_STATE_PRESSED);

    lv_obj_t *lbl_back = lv_label_create(btn_back);
    lv_label_set_text(lbl_back, LV_SYMBOL_LEFT);
    lv_obj_center(lbl_back);

    lv_obj_add_event_cb(btn_back, cb_btn_back, LV_EVENT_CLICKED, NULL);

    // ============================================================
    // Loop button (góc phải trên)
    // ============================================================
    
    btn_loop = lv_btn_create(ui_audioplayer);
    lv_obj_set_size(btn_loop, 40, 30);
    lv_obj_align(btn_loop, LV_ALIGN_TOP_RIGHT, -5, 5);
    lv_obj_add_style(btn_loop, &style_ctrl_btn, LV_STATE_DEFAULT);
    lv_obj_add_style(btn_loop, &style_ctrl_btn_pressed_2, LV_STATE_PRESSED);

    lbl_loop = lv_label_create(btn_loop);
    lv_label_set_text(lbl_loop, LV_SYMBOL_LOOP);
    lv_obj_center(lbl_loop);
    lv_obj_set_style_text_opa(lbl_loop, LV_OPA_40, 0);

    lv_obj_add_event_cb(btn_loop, cb_btn_loop, LV_EVENT_CLICKED, NULL);

    // ============================================================
    // Song name — chữ chạy vòng nếu quá dài
    // ============================================================
    ui_lblSongName = lv_label_create(ui_audioplayer);
    lv_label_set_text(ui_lblSongName, "No song selected");
    lv_obj_set_width(ui_lblSongName, 240);
    lv_obj_align(ui_lblSongName, LV_ALIGN_TOP_MID, 0, 45);
    lv_obj_set_style_text_align(ui_lblSongName, LV_TEXT_ALIGN_CENTER, 0);
    lv_label_set_long_mode(ui_lblSongName, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_add_style(ui_lblSongName, &style_song_name, 0);

    // ============================================================
    // Progress slider
    // ============================================================
    ui_sliderProgress = lv_slider_create(ui_audioplayer);
    lv_obj_set_width(ui_sliderProgress, 260);
    lv_obj_align(ui_sliderProgress, LV_ALIGN_CENTER, 0, -20);
    lv_slider_set_range(ui_sliderProgress, 0, 100);
    lv_slider_set_value(ui_sliderProgress, 0, LV_ANIM_OFF);

    // Áp style cho 3 phần của slider:
    // LV_PART_MAIN       = track nền
    // LV_PART_INDICATOR   = phần đã fill
    // LV_PART_KNOB        = nút kéo tròn
    lv_obj_add_style(ui_sliderProgress, &style_progress_main, LV_PART_MAIN);
    lv_obj_add_style(ui_sliderProgress, &style_progress_indicator, LV_PART_INDICATOR);
    lv_obj_add_style(ui_sliderProgress, &style_progress_knob, LV_PART_KNOB);

    lv_obj_add_event_cb(ui_sliderProgress, cb_slider_progress, LV_EVENT_VALUE_CHANGED, NULL);

    // ============================================================
    // Time labels
    // ============================================================
    ui_lblTimeElapsed = lv_label_create(ui_audioplayer);
    lv_label_set_text(ui_lblTimeElapsed, "00:00");
    lv_obj_align(ui_lblTimeElapsed, LV_ALIGN_CENTER, -115, 0);
    lv_obj_set_style_text_color(ui_lblTimeElapsed, lv_color_hex(0xAAAAAA), 0);

    ui_lblTimeTotal = lv_label_create(ui_audioplayer);
    lv_label_set_text(ui_lblTimeTotal, "00:00");
    lv_obj_align(ui_lblTimeTotal, LV_ALIGN_CENTER, 115, 0);
    lv_obj_set_style_text_color(ui_lblTimeTotal, lv_color_hex(0xAAAAAA), 0);

    // ============================================================
    // Control buttons: Prev | Play/Pause | Next
    // ============================================================

    // Container ngang cho 3 nút
    lv_obj_t *ctrl_row = lv_obj_create(ui_audioplayer);
    lv_obj_set_size(ctrl_row, 200, 50);
    lv_obj_align(ctrl_row, LV_ALIGN_CENTER, 0, 35);
    lv_obj_set_flex_flow(ctrl_row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ctrl_row, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_opa(ctrl_row, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ctrl_row, 0, 0);
    lv_obj_set_style_pad_all(ctrl_row, 0, 0);
    lv_obj_clear_flag(ctrl_row, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_clear_flag(ctrl_row, LV_OBJ_FLAG_CLICKABLE);

    // --- Previous ---
    btn_prev = lv_btn_create(ctrl_row);
    lv_obj_set_size(btn_prev, 45, 45);
    lv_obj_add_style(btn_prev, &style_ctrl_btn, LV_STATE_DEFAULT);
    lv_obj_add_style(btn_prev, &style_ctrl_btn_pressed, LV_STATE_PRESSED);
    lv_obj_t *lbl_prev = lv_label_create(btn_prev);
    lv_label_set_text(lbl_prev, LV_SYMBOL_PREV);
    lv_obj_center(lbl_prev);
    lv_obj_add_event_cb(btn_prev, cb_btn_prev, LV_EVENT_CLICKED, NULL);

    // --- Play / Pause (lớn hơn) ---
    ui_btnPlayPause = lv_btn_create(ctrl_row);
    lv_obj_set_size(ui_btnPlayPause, 45, 45);
    lv_obj_add_style(ui_btnPlayPause, &style_ctrl_btn, LV_STATE_DEFAULT);
    lv_obj_add_style(ui_btnPlayPause, &style_ctrl_btn_pressed, LV_STATE_PRESSED);
    // Viền tròn cho nút play
    lv_obj_set_style_border_width(ui_btnPlayPause, 2, LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnPlayPause, lv_color_hex(0xFFFFFF), LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_btnPlayPause, LV_RADIUS_CIRCLE, 0);

    ui_lblBtnPlayPause = lv_label_create(ui_btnPlayPause);
    lv_label_set_text(ui_lblBtnPlayPause, LV_SYMBOL_PAUSE);
    lv_obj_set_style_text_color(ui_lblBtnPlayPause, lv_color_hex(0xFFFFFF), 0);
    lv_obj_center(ui_lblBtnPlayPause);
    lv_obj_add_event_cb(ui_btnPlayPause, cb_btn_play_pause, LV_EVENT_CLICKED, NULL);

    // --- Next ---
    btn_next = lv_btn_create(ctrl_row);
    lv_obj_set_size(btn_next, 45, 45);
    lv_obj_add_style(btn_next, &style_ctrl_btn, LV_STATE_DEFAULT);
    lv_obj_add_style(btn_next, &style_ctrl_btn_pressed, LV_STATE_PRESSED);
    lv_obj_t *lbl_next = lv_label_create(btn_next);
    lv_label_set_text(lbl_next, LV_SYMBOL_NEXT);
    lv_obj_center(lbl_next);
    lv_obj_add_event_cb(btn_next, cb_btn_next, LV_EVENT_CLICKED, NULL);

    // ============================================================
    // Volume: icon + slider
    // ============================================================
    lv_obj_t *vol_row = lv_obj_create(ui_audioplayer);
    lv_obj_set_size(vol_row, 240, 30);
    lv_obj_align(vol_row, LV_ALIGN_BOTTOM_MID, 0, -10);
    lv_obj_set_flex_flow(vol_row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(vol_row, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_opa(vol_row, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(vol_row, 0, 0);
    lv_obj_set_style_pad_column(vol_row, 8, 0);
    lv_obj_clear_flag(vol_row, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_clear_flag(vol_row, LV_OBJ_FLAG_CLICKABLE);

    lbl_volume_icon = lv_label_create(vol_row);
    lv_label_set_text(lbl_volume_icon, LV_SYMBOL_VOLUME_MAX);
    lv_obj_set_style_text_color(lbl_volume_icon, lv_color_hex(0xAAAAAA), 0);

    ui_sliderVolume = lv_slider_create(vol_row);
    lv_obj_set_flex_grow(ui_sliderVolume, 1);
    lv_obj_set_height(ui_sliderVolume, 6);
    lv_slider_set_range(ui_sliderVolume, 0, 100);
    lv_slider_set_value(ui_sliderVolume, 0, LV_ANIM_OFF);

    lv_obj_add_style(ui_sliderVolume, &style_progress_main, LV_PART_MAIN);
    lv_obj_add_style(ui_sliderVolume, &style_progress_indicator, LV_PART_INDICATOR);
    lv_obj_add_style(ui_sliderVolume, &style_progress_knob, LV_PART_KNOB);

    lv_obj_add_event_cb(ui_sliderVolume, cb_slider_volume, LV_EVENT_VALUE_CHANGED, NULL);

    uic_audioplayer = ui_audioplayer;

}

void ui_audioplayer_screen_destroy(void)
{
    if(ui_audioplayer) lv_obj_del(ui_audioplayer);

    // NULL screen variables
    uic_audioplayer = NULL;
    ui_audioplayer = NULL;
}
